### ISSUE TITLE
`note`: Minimalistic Note Taking

### ISSUE THREAD

**Issue by bdazl** [toolleeo/awesome-cli-apps-in-a-csv#90]
Hello!

I would like to add my contribution to the pool of awesome terminal applications, in the category of `Note Taking`:
* name: `note`
* git: https://github.com/bdazl/note
* description: Minimalistic Note Taking

**Comment by toolleeo** [comment]
Hello, do you want me to add, or you prefer to become a contributor making a pull request?

In the latter case, please modify only the CSV source file, as explained in the README.

**Comment by bdazl** [comment]
Thank you for the question, I can very well make a pull request myself, later today!
