### ISSUE TITLE
add rsnapshot backup script

### ISSUE THREAD

**Issue by pklausner** [toolleeo/awesome-cli-apps-in-a-csv#95]
name: rsnapshot

homepage: https://rsnapshot.org

git: https://github.com/rsnapshot/rsnapshot

description: A filesystem snapshot utility based on rsync. It manages a rotation schedule when to discard older backup, e.g. from hourly to yearly. The Perl code makes extensive use of hard links and greatly reduces the disk space required.

**Comment by toolleeo** [comment]
Hello, I will be happy to add it.

Do you prefer proceeding with a pull request, so that you get the credit of the addition, or should I add it myself?

**Comment by toolleeo** [comment]
Added.
